syntax = "proto3";

package mxstream;

message MxData {
    bytes fmap = 1;
    uint32 port_id = 2;
    uint32 ctx_id = 3;
}

message OfPorts{
    repeated uint32 port_id = 1;
    repeated uint64 size = 2;
    uint32 ctx_id = 3;
}

message LockData {
    uint32 group_id = 1;
}

message Ping {
    bool recv = 1;
    string msg = 2;
}

message DfpData {
    bytes dfp_bytes = 1;
    repeated uint32 group_id = 2;
    string uuid = 3;
}

message Uuid{
    string id = 1;
}

service MxService {
    rpc try_lock (LockData) returns (Ping);
    rpc unlock (LockData) returns (Ping);
    rpc connect_dfp(DfpData) returns (Ping);
    rpc close_process(DfpData) returns (Ping);
    rpc send_ifmap(stream MxData) returns (Ping);
    rpc recevice_ofmap(OfPorts) returns (stream MxData);
    rpc heartbeat(Uuid) returns (Ping);
    rpc local_heartbeat(LockData) returns (Ping);
}