# address to listen on
#
# * defaults to 127.0.0.1 to limit to local traffic
#
# * set to 0.0.0.0 or an interface address to accept network traffic
#LISTEN_ADDRESS="127.0.0.1"
LISTEN_ADDRESS="/run/mxa_manager/"

# the daemon will use 3 ports in order starting with this number
#
# NOTE: be sure to make sure your client applications use these ports too!
BASE_PORT=10000
