# address to listen on
#
# * Linux defaults to UNIX socket in /run/mxa_manager/
# * Windows defaults to 127.0.0.1 to use local TCP connections
# * set to 0.0.0.0 or an interface address to accept network traffic
#
LISTEN_ADDRESS="/run/mxa_manager/"

# the daemon will use 3 ports in order starting with this number
#
# NOTE: be sure to make sure your client applications use these ports too!
BASE_PORT=10000

# mxa-manager's log level (to system log, i.e. journalctl or syslog)
#
# higher levels give more information, useful for debugging
#
# options are: off, low (default), medium, high
LOG_LEVEL=low

# how frequently to poll for hardware stats (in milliseconds)
#
# this includes chip temperature, power usage, and pipeline pressure
#
# lower values give faster and more accurate averages, but will
# increase the CPU usage of mxa-manager
#
# generally speaking, values below 100ms are not recommended
# default is 500 ms
HW_MONITOR_INTERVAL=500
