# Socket/address to listen on
#
# * use a folder path to use UNIX sockets
# * use 127.0.0.1 for IP networking, limited to localhost
# * set to 0.0.0.0 or an interface address to accept external network traffic
#
#LISTEN_ADDRESS="127.0.0.1"
LISTEN_ADDRESS="/run/mxa_manager/"

# The daemon will use 3 ports/socket files in order starting with this number.
# For example, "10000" will use 10000, 10001, and 10002
BASE_PORT=10000
